### ISSUE TITLE
Requesting zip compression

### ISSUE THREAD

**Issue by NickDatLe** [xtream1101/s3-tar#8]
Hi there - this is a great tool and it solves some problems for me. Is there any plans to add ".zip" file formats in the future?

**Comment by xtream1101** [comment]
I looked into it and could not find a way to stream the zip data in parts to a remote file (doing so with s3 multi part upload). The only way I found was to create the zip file fully locally (either on disk or in mem) then upload back which is not what this tool is solving for since that can be done pretty simply. 

Any reason you need a zip file specifically?
